"""Pydantic models and TypedDicts for the LangGraph agent state."""
from typing import Any, TypedDict

class AgentState(TypedDict, total=False):
    """The state object passed between LangGraph nodes.

    All fields are optional (total=False) so that the graph can
    initialise with just the user query and build up over time.
    """

    query: str
    """Original natural-language query from the user."""

    messages: list[dict[str, Any]]
    """Full conversation history (system + user + assistant + tool messages)."""

    tool_calls: list[dict[str, Any]]
    """Tool calls requested by the LLM (from Groq's response)."""

    tool_results: list[dict[str, Any]]
    """Results returned from executing tool calls."""

    sql_query: str | None
    """The SQL query generated by the LLM (if any)."""

    response: str | None
    """Final natural-language response to the user."""

    error: str | None
    """Error message if any node failed."""