"""Scoring metrics for evaluating LLM tool-calling accuracy.

Two metrics:
    1. Query Match Score (0-1): AST-based structural comparison of SQL queries.
    2. Result Match Score (0-1): Row-level comparison of query result sets.
"""

from __future__ import annotations

import re
from typing import Any

try:
    import sqlparse
except ImportError:
    sqlparse = None  # Fallback: use string-based comparison


# ──────────────────────────────────────────────
# Query Match Score (SQL AST structural similarity)
# ──────────────────────────────────────────────


def _normalise_ast(sql: str) -> str:
    """Parse SQL into an AST, normalise it, and return a canonical string.

    Normalisation steps:
        - Lowercase all keywords.
        - Sort SELECT columns alphabetically.
        - Sort WHERE conditions (removing parentheses differences).
        - Sort ORDER BY columns.
        - Remove extra whitespace and semicolons.
        - Standardise quoted identifiers.
    """
    if not sql:
        return ""

    sql = sql.strip().rstrip(";").strip()
    sql = sql.lower()

    # Normalise whitespace around operators and parentheses
    sql = re.sub(r"\s+", " ", sql)
    sql = re.sub(r"\s*=\s*", " = ", sql)
    sql = re.sub(r"\s*!=\s*", " != ", sql)
    sql = re.sub(r"\s*>\s*", " > ", sql)
    sql = re.sub(r"\s*<\s*", " < ", sql)
    sql = re.sub(r"\s*>=\s*", " >= ", sql)
    sql = re.sub(r"\s*<=\s*", " <= ", sql)
    sql = re.sub(r"\s*,\s*", ", ", sql)
    sql = re.sub(r"\s*\(\s*", " ( ", sql)
    sql = re.sub(r"\s*\)\s*", " ) ", sql)
    sql = re.sub(r"\s+", " ", sql).strip()
    sql = re.sub(r"\s'", "'", sql)
    sql = re.sub(r"'\s", "'", sql)

    return sql


def _tokenise_sql(sql: str) -> list[str]:
    """Tokenise a normalised SQL string into meaningful tokens."""
    if not sql:
        return []
    # Split on whitespace and keep quoted strings as single tokens
    tokens: list[str] = []
    for token in re.findall(r"'[^']*'|\S+", sql):
        tokens.append(token)
    return tokens


def _sql_token_similarity(expected: str, actual: str) -> float:
    """Compute token-based similarity between two SQL queries.

    Uses a weighted approach where structural keywords (SELECT, FROM, WHERE, etc.)
    are weighted more heavily than values.
    """
    expected_norm = _normalise_ast(expected)
    actual_norm = _normalise_ast(actual)

    if not expected_norm and not actual_norm:
        return 1.0
    if not expected_norm or not actual_norm:
        return 0.0

    exp_tokens = _tokenise_sql(expected_norm)
    act_tokens = _tokenise_sql(actual_norm)

    if not exp_tokens and not act_tokens:
        return 1.0
    if not exp_tokens or not act_tokens:
        return 0.0

    # Structural keywords get higher weight
    structure_keywords: set[str] = {
        "select", "from", "where", "group", "by", "having",
        "order", "limit", "as", "on", "join", "inner", "left",
        "right", "full", "outer", "cross", "and", "or", "not",
        "in", "between", "like", "is", "null", "distinct",
        "asc", "desc",
    }

    # Identify matching tokens using sequence-based matching (preserving order matters)
    # Use LCS (Longest Common Subsequence) approach
    m, n = len(exp_tokens), len(act_tokens)
    dp = [[0] * (n + 1) for _ in range(m + 1)]

    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if exp_tokens[i - 1] == act_tokens[j - 1]:
                dp[i][j] = dp[i - 1][j - 1] + 1
            else:
                dp[i][j] = max(dp[i - 1][j], dp[i][j - 1])

    lcs_length = dp[m][n]

    # Weight by structural importance
    weighted_matches = 0.0
    weighted_total = 0.0

    for token in exp_tokens:
        weight = 3.0 if token.rstrip(",").lower() in structure_keywords else 1.0
        weighted_total += weight
        if token in act_tokens:
            weighted_matches += weight

    if weighted_total == 0:
        return 0.0

    # Combine LCS ratio with weighted token overlap
    lcs_ratio = (2.0 * lcs_length) / (m + n) if (m + n) > 0 else 1.0
    token_overlap = weighted_matches / weighted_total

    # Weighted combination: LCS (60%) + token overlap (40%)
    return 0.6 * lcs_ratio + 0.4 * token_overlap


def compute_query_match_score(expected_sql: str, actual_sql: str) -> dict[str, Any]:
    """Compare two SQL queries and return a structural similarity score (0-1).

    Args:
        expected_sql: The ground-truth SQL query.
        actual_sql: The SQL query generated by the LLM.

    Returns:
        Dict with:
            - score: 0.0 to 1.0 similarity score
            - expected_normalised: Normalised version of expected SQL
            - actual_normalised: Normalised version of actual SQL
            - details: Explanation of the match quality
    """
    if not actual_sql:
        return {
            "score": 0.0,
            "expected_normalised": _normalise_ast(expected_sql),
            "actual_normalised": "",
            "details": "No SQL query was generated by the LLM.",
        }

    score = _sql_token_similarity(expected_sql, actual_sql)

    if score >= 0.95:
        details = "Excellent match — queries are structurally identical or near-identical."
    elif score >= 0.80:
        details = "Good match — minor differences in column order, aliasing, or formatting."
    elif score >= 0.60:
        details = "Moderate match — some structural differences in clauses or conditions."
    elif score >= 0.30:
        details = "Poor match — significant structural differences."
    else:
        details = "Very poor or no match — queries are fundamentally different."

    return {
        "score": round(score, 4),
        "expected_normalised": _normalise_ast(expected_sql),
        "actual_normalised": _normalise_ast(actual_sql),
        "details": details,
    }


# ──────────────────────────────────────────────
# Result Match Score (row-level result comparison)
# ──────────────────────────────────────────────


def compute_result_match_score(
    expected_results: list[dict[str, Any]],
    actual_results: list[dict[str, Any]],
) -> dict[str, Any]:
    """Compare two result sets and return a row-level match score (0-1).

    Args:
        expected_results: Results from the ground-truth SQL query.
        actual_results: Results from the LLM-generated SQL query.

    Returns:
        Dict with:
            - score: 0.0 to 1.0 similarity score
            - expected_row_count: Number of rows in expected results
            - actual_row_count: Number of rows in actual results
            - matching_rows: Number of rows that match exactly
            - details: Explanation of the match quality
    """
    exp_count = len(expected_results)
    act_count = len(actual_results)

    if exp_count == 0 and act_count == 0:
        return {
            "score": 1.0,
            "expected_row_count": 0,
            "actual_row_count": 0,
            "matching_rows": 0,
            "details": "Both queries returned no rows — perfect match.",
        }

    if exp_count == 0 or act_count == 0:
        score = 0.0
        matching = 0
        if exp_count == 0 and act_count > 0:
            details = f"Expected 0 rows but got {act_count} rows — no match."
        else:
            details = f"Expected {exp_count} rows but got 0 rows — no match."
        return {
            "score": score,
            "expected_row_count": exp_count,
            "actual_row_count": act_count,
            "matching_rows": matching,
            "details": details,
        }

    # Normalise rows: sort by a stable key and compare
    def _row_key(row: dict[str, Any]) -> str:
        """Create a stable string key for a row for comparison."""
        return str(sorted((k, str(v)) for k, v in row.items()))

    exp_set = {_row_key(r) for r in expected_results}
    act_set = {_row_key(r) for r in actual_results}

    matching = len(exp_set & act_set)
    total_unique = len(exp_set | act_set)

    if total_unique == 0:
        row_similarity = 1.0
    else:
        row_similarity = matching / total_unique

    # Also factor in row count proximity
    max_count = max(exp_count, act_count)
    min_count = min(exp_count, act_count)
    count_proximity = min_count / max_count if max_count > 0 else 1.0

    # Composite: 70% row similarity, 30% count proximity
    score = 0.7 * row_similarity + 0.3 * count_proximity

    if score >= 0.95:
        details = "Excellent match — result sets are identical or nearly identical."
    elif score >= 0.80:
        details = "Good match — most rows are the same with minor differences."
    elif score >= 0.60:
        details = "Moderate match — some rows match but there are notable differences."
    elif score >= 0.30:
        details = "Poor match — few rows match between the result sets."
    else:
        details = "Very poor or no match — result sets are fundamentally different."

    return {
        "score": round(score, 4),
        "expected_row_count": exp_count,
        "actual_row_count": act_count,
        "matching_rows": matching,
        "details": details,
    }